-- MySQL Script generated by MySQL Workbench
-- Thu Jun 25 12:04:26 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_IndyCrawler
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_IndyCrawler` ;

-- -----------------------------------------------------
-- Schema db_IndyCrawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_IndyCrawler` DEFAULT CHARACTER SET utf8 ;
USE `db_IndyCrawler` ;

-- -----------------------------------------------------
-- Table `db_IndyCrawler`.`tb_Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_IndyCrawler`.`tb_Locations` ;

CREATE TABLE IF NOT EXISTS `db_IndyCrawler`.`tb_Locations` (
  `locationId` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `fullName` TEXT NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`locationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_IndyCrawler`.`tb_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_IndyCrawler`.`tb_category` ;

CREATE TABLE IF NOT EXISTS `db_IndyCrawler`.`tb_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'cultural\nmusical\nesportivo\nteatro';


-- -----------------------------------------------------
-- Table `db_IndyCrawler`.`tb_Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_IndyCrawler`.`tb_Events` ;

CREATE TABLE IF NOT EXISTS `db_IndyCrawler`.`tb_Events` (
  `eventId` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `startDate` DATETIME NULL DEFAULT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `url` TEXT NULL,
  `price` TEXT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `locationId` INT NOT NULL,
  `tb_category_id` INT NOT NULL,
  PRIMARY KEY (`eventId`, `locationId`, `tb_category_id`),
  INDEX `fk_tb_Events_tb_category1_idx` (`tb_category_id` ASC),
  CONSTRAINT `fk_tb_Events_tb_Locations`
    FOREIGN KEY (`locationId`)
    REFERENCES `db_IndyCrawler`.`tb_Locations` (`locationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Events_tb_category1`
    FOREIGN KEY (`tb_category_id`)
    REFERENCES `db_IndyCrawler`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
